log out of converse when logging out of roundcube
conversejs/roundcube-plugin pull request #2
Opened 2017-10-20 11:17 UTC by HanakoSeishin

2017-10-20 12:27 UTC, devurandom requested changes

2017-10-20 12:27 UTC, devurandom commented on js/converse-rcmail.js
> +                //console.log('logout');
Could you please remove this comment?

2017-10-21 09:53 UTC, devurandom commented
Thanks! Can you please squash the two commits into one?

2017-10-21 11:00 UTC, HanakoSeishin commented
Sorry, now idea how to do so. I'm totally new here and the whole interface is still confusing and overwhelming.

2017-10-21 11:46 UTC, devurandom commented
The first result of the web search I did explains quite well how to do it: http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html

2017-10-21 13:58 UTC, HanakoSeishin commented
I'm terribly sorry, but explaining quite well how make a barrel roll doesn't help if one doesn't know how to take off in the first place. I was under impression that the purpose of this site, well at least part of it, is making it easy for people to contribute. But I guess I was wrong. Maybe I'll come back some day when I can get what that article is even talking about.

2017-10-21 14:50 UTC, devurandom commented
You're right, the site is quite more advanced by now, than I realised. I can squash the commits for you from the web-interface.

2017-10-21 14:50 UTC, merged

2017-10-21 14:55 UTC, devurandom commented
For whatever reason this did not go well, so I manually edited the history. Should be fine now.

Thanks for the contribution!

2023-02-27 17:40 UTC, mckaygerhard commented
solution for to #10  and #5 thanks